//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTech.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public int ID { get; set; }
        public string AccountNumber { get; set; }
        public string AccountOwner { get; set; }
        public int BankNameID { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public decimal Balance { get; set; }
        public string ClientDate { get; set; }
        public string ServerDate { get; set; }
        public string ClientTime { get; set; }
        public string ServerTime { get; set; }
        public int UserID { get; set; }
        public string Address { get; set; }
        public string Branch { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public int AccountTypeID { get; set; }
    
        public virtual BankAccountType BankAccountType { get; set; }
        public virtual BankName BankName { get; set; }
    }
}
