//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTech.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyBody
    {
        public int ID { get; set; }
        public int BuyID { get; set; }
        public int PeopleD { get; set; }
        public bool Active { get; set; }
    
        public virtual People People { get; set; }
        public virtual BuyDetail BuyDetail { get; set; }
    }
}
