//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTech.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityTemp
    {
        public int ID { get; set; }
        public int ProvinceID { get; set; }
        public string Name { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    
        public virtual ProvinceTemp ProvinceTemp { get; set; }
    }
}
