//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTech.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsActivity
    {
        public int ID { get; set; }
        public int GoodsID { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime ServerDate { get; set; }
        public int UserID { get; set; }
        public decimal UnitCount { get; set; }
        public int SingleCount { get; set; }
        public decimal PackageCount { get; set; }
        public decimal Price { get; set; }
        public string Gain { get; set; }
        public int TypeID { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual GoodsActivityType GoodsActivityType { get; set; }
        public virtual User User { get; set; }
    }
}
