//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTech.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.BuyDetail = new HashSet<BuyDetail>();
            this.GoodsActivity = new HashSet<GoodsActivity>();
            this.GoodsCode = new HashSet<GoodsCode>();
            this.GoodsWarehouse = new HashSet<GoodsWarehouse>();
            this.GoodsWarehouseActivity = new HashSet<GoodsWarehouseActivity>();
            this.SailDetail = new HashSet<SailDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int GroupID { get; set; }
        public int UnitID { get; set; }
        public int UnitCount { get; set; }
        public decimal UnitInventory { get; set; }
        public int SingleInventory { get; set; }
        public bool Active { get; set; }
        public byte[] Image { get; set; }
        public int ReOrderPointCount { get; set; }
        public decimal PackageInventory { get; set; }
        public int PackageID { get; set; }
        public decimal UnitWeight { get; set; }
        public decimal UnitVolume { get; set; }
        public decimal BuyPrice { get; set; }
        public decimal AverageBuyPrice { get; set; }
        public string CreateDate { get; set; }
        public int CreateUserID { get; set; }
        public string Description { get; set; }
        public int SingleMinimumOrderCount { get; set; }
        public decimal UnitTransportPrice { get; set; }
        public bool BlackList { get; set; }
        public decimal TaxesPercent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyDetail> BuyDetail { get; set; }
        public virtual GoodsGroup GoodsGroup { get; set; }
        public virtual GoodsUnit GoodsUnit { get; set; }
        public virtual GoodsUnit GoodsUnit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsActivity> GoodsActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsCode> GoodsCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsWarehouse> GoodsWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsWarehouseActivity> GoodsWarehouseActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SailDetail> SailDetail { get; set; }
    }
}
