//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTech.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsWarehouse
    {
        public int WarehouseID { get; set; }
        public int GoodsID { get; set; }
        public decimal UnitInventory { get; set; }
        public int SingleInventory { get; set; }
        public decimal PackageInventory { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
