//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTech.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsCode
    {
        public int ID { get; set; }
        public int GoodsID { get; set; }
        public string Code { get; set; }
        public bool Active { get; set; }
        public bool Default { get; set; }
    
        public virtual Goods Goods { get; set; }
    }
}
