//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTech.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Path
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int RegionID { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public string ClientDate { get; set; }
        public string ServerDate { get; set; }
        public string ClientTime { get; set; }
        public string ServerTime { get; set; }
        public int UserID { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
