//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTech.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public People()
        {
            this.BuyBody = new HashSet<BuyBody>();
            this.PeopleActivity = new HashSet<PeopleActivity>();
            this.SailBody = new HashSet<SailBody>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public int GroupID { get; set; }
        public bool Active { get; set; }
        public int VisitorID { get; set; }
        public int ProvinceID { get; set; }
        public int CityID { get; set; }
        public int RegionID { get; set; }
        public int PathID { get; set; }
        public int NumberInPath { get; set; }
        public byte[] Image { get; set; }
        public decimal Credit { get; set; }
        public decimal Balance { get; set; }
        public string Message { get; set; }
        public string Description { get; set; }
        public bool BlackList { get; set; }
        public string Code { get; set; }
        public bool Special { get; set; }
        public string CreateDate { get; set; }
        public int CreateUserID { get; set; }
        public int CreateVisitorID { get; set; }
        public int Status { get; set; }
        public string NationalCode { get; set; }
        public string EconomicCode { get; set; }
        public string PostalCode { get; set; }
        public int TypeID { get; set; }
        public int AllowedFactorCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyBody> BuyBody { get; set; }
        public virtual PeopleGroup PeopleGroup { get; set; }
        public virtual PeopleType PeopleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeopleActivity> PeopleActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SailBody> SailBody { get; set; }
    }
}
