//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyTech.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personnel()
        {
            this.Customer = new HashSet<Customer>();
            this.PersonnelActivity = new HashSet<PersonnelActivity>();
            this.SailBody = new HashSet<SailBody>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public decimal Credit { get; set; }
        public decimal Balance { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
        public int PersonnelTypeID { get; set; }
        public decimal Salary { get; set; }
        public byte[] Image { get; set; }
        public string CreateDate { get; set; }
        public int CreateUserID { get; set; }
        public bool IsSupervisor { get; set; }
        public int SupervisorID { get; set; }
        public decimal SupervisorPercent { get; set; }
        public decimal CashRewardPercent { get; set; }
        public decimal FaildCheckPercent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual PersonnelType PersonnelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonnelActivity> PersonnelActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SailBody> SailBody { get; set; }
    }
}
